sudo: false

language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

install:
  - "go version"
  - "go env"
  - "mkdir -p $GOPATH/bin"
  - "curl -s https://glide.sh/get | sh"

script:
  - "glide install"
  - "go build"
  - "./scripts/run-tests.sh"
