language: python

python:
  - 2.7
  - 3.2

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"

install:
  - "pip install -r requirements.txt --use-mirrors"
  - "./scripts/notable -d > /tmp/notable.log 2>&1 &"
  - "sleep 2"

script:
  - "curl localhost:8083"
  - "nosetests -v"
  - "echo Server log:"
  - "cat /tmp/notable.log"
