language: python
python:
  - 2.7
  - 3.2
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "./scripts/notable -d -f"
  - "sleep 2"
script:
  - "export BROWSER=FIREFOX"
  - "nosetests -v"
