language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"

install:
  - "pip install -r requirements.txt --use-mirrors"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi"
  - "./scripts/notable -d -f --no-browser > /tmp/notable.log 2>&1 &"
  - "sleep 2"

script:
  - "curl localhost:8083"
  - "nosetests -v"
  - "echo Server log:"
  - "cat /tmp/notable.log"
